In [1]:
%pip install evaluate
%pip install sacrebleu

Requirement already satisfied: evaluate in /usr/local/lib/python3.13/dist-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.34.2)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (3.32.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.24.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: sacrebleu in /usr/local/lib/python3.13/dist-packages (2.6.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.13/dist-packages (from sacrebleu) (4.4.0)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.13/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from sacrebleu) (2.1.3)
Requirement already satisfied: colorama in /usr/local/lib/python3.13/dist-packages (from sacrebleu) (0.4.6)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (from sacrebleu) (6.1.2)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Les importations
import evaluate
import matplotlib.pyplot as plt
import numpy as np
#import tensorflow as tf
import torch
from datasets import Dataset, DatasetDict, load_dataset
#from comet import download_model, load_from_checkpoint
from torch.cuda.amp import GradScaler, autocast
from transformers import (
    AutoModelForCausalLM,
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    DataCollatorForSeq2Seq,
    EarlyStoppingCallback,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    TrainerCallback,
    get_linear_schedule_with_warmup,
)

SOURCE_LANG_CODE_NLLB =  "fra_Latn" 
TARGET_LANG_CODE_NLLB =  "arb_Latn" 
max_input_length = 128
max_target_length = 128


class MemoryCleanupCallback(TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        torch.cuda.empty_cache()  # Libérer la mémoire GPU inutilisée

class LossTrackerCallback(TrainerCallback):
    def __init__(self):
        self.history = {
            "step": [],
            "train_loss": [],
            "eval_loss": []
        }

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs is None:
            return
        
        if "loss" in logs:
            self.history["step"].append(state.global_step)
            self.history["train_loss"].append(logs["loss"])
            self.history["eval_loss"].append(None)

        if "eval_loss" in logs:
            self.history["step"].append(state.global_step)
            self.history["train_loss"].append(None)
            self.history["eval_loss"].append(logs["eval_loss"])


def training (modele_name, train_test_val_dataset) : 
    
    loss_tracker = LossTrackerCallback()
    model = AutoModelForSeq2SeqLM.from_pretrained(modele_name)
    tokenizer = AutoTokenizer.from_pretrained(modele_name)

    def postprocess_text(preds, labels):
        preds = [pred.strip() for pred in preds]
        labels = [[label.strip()] for label in labels]  # ROUGE/METEOR attend des listes imbriquées
        return preds, labels

    def compute_metrics(eval_preds):
        preds, labels = eval_preds

        preds = np.where(preds != -100, preds, tokenizer.pad_token_id)
        labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
        
        if isinstance(preds, tuple):
            preds = preds[0]

        # Décodage des prédictions et labels
        decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
        #labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
        decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

        # Nettoyage du texte
        decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

        # Charger les métriques
        bleu_metric = evaluate.load("sacrebleu")
        rouge_metric = evaluate.load("rouge")
        meteor_metric = evaluate.load("meteor")

        # 🏆 Calcul des métriques
        bleu_result = bleu_metric.compute(predictions=decoded_preds, references=decoded_labels)
        rouge_result = rouge_metric.compute(predictions=decoded_preds, references=decoded_labels)
        meteor_result = meteor_metric.compute(predictions=decoded_preds, references=decoded_labels)

        # 📊 Récupération des scores
        result = {
            "bleu": bleu_result["score"],
            "rouge": rouge_result["rougeL"],  # Utilisation du score ROUGE-L
            "meteor": meteor_result["meteor"],
        }

        # Arrondir les scores
        result = {k: round(v, 4) for k, v in result.items()}
        return result


    def extract_langage(examples) :
        # On va extraire le langage arabe et le langage français
        inputs = [fr['fr'] for fr in examples["translation"]]
        target = [arb['arb'] for arb in examples["translation"]]
        return {'inputs' : inputs, 'target' : target}



    def preprocess_function(examples):
        tokenizer.src_lang = SOURCE_LANG_CODE_NLLB
        model_inputs = tokenizer(
            examples["inputs"],
            max_length=max_input_length,
            truncation=True
        )

        # Nettoyer les cibles : enlever None ou chaînes vides
        clean_targets = []
        for t in examples["target"]:
            if isinstance(t, str) and t.strip():
                clean_targets.append(t)
            else:
                clean_targets.append(" ")

        tokenizer.tgt_lang = TARGET_LANG_CODE_NLLB
        labels = tokenizer(
            clean_targets,
            max_length=max_target_length,
            truncation=True,
            text_target=clean_targets  # Pour compatibilité future
        )

        model_inputs["labels"] = labels["input_ids"]
        
        return model_inputs

    
    def train_and_valid_loss() :

        loss_dict = loss_tracker.history
        steps = loss_dict["step"]

        train_loss = [
            l for l in loss_dict["train_loss"] if l is not None]
        train_steps = [
            s for s, l in zip(steps, loss_dict["train_loss"]) if l is not None]

        eval_loss = [
            l for l in loss_dict["eval_loss"] if l is not None
        ]
        eval_steps = [
            s for s, l in zip(steps, loss_dict["eval_loss"]) if l is not None
        ]

        plt.plot(train_steps, train_loss, label="Train Loss")
        plt.plot(eval_steps, eval_loss, label="Validation Loss")
        plt.xlabel("Steps")
        plt.ylabel("Loss")
        plt.legend()
        plt.grid(True)
        plt.show()


    # On va appliquer la fonction sur notre dataset
    train_dataset = train_test_val_dataset.map(extract_langage, batched=True, remove_columns=["translation"])
    # On va appliquer la fonction sur notre dataset
    train_dataset = train_dataset.map(preprocess_function, batched=True, remove_columns=["inputs", "target"])
    # Dataloader
    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model, label_pad_token_id=-100)


    early =  EarlyStoppingCallback(early_stopping_patience = 5)
    #loss_tracker = LossTrackerCallback()


    training_args = Seq2SeqTrainingArguments(
        output_dir=f"../src/{modele_name}",
        report_to="none",
        #hub_model_id= os.environ.get('HUB_ID_2'),  # ✅ Ajoute ton Repo ID
        eval_strategy="steps",
        eval_steps=100,              
        logging_steps=100, 
        learning_rate=2e-5,
        #learning_rate=1e-5,
        gradient_checkpointing=True,  # ✅ Active la réduction mémoire
        #use_cache = False,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=50,
        metric_for_best_model="eval_loss",
        predict_with_generate=True,
        fp16=True, 
        #push_to_hub=True,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        save_strategy="steps",
        #save_steps = 50,
        #resume_from_checkpoint=True,
        gradient_accumulation_steps=2,

    )




    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset["train"],
        eval_dataset=train_dataset["val"],
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        callbacks=[early,loss_tracker, MemoryCleanupCallback], #CheckpointCleanupCallback()
    )
    torch.cuda.empty_cache()  # Libérer la mémoire GPU inutilisée

    trainer.train()

    results = trainer.evaluate(train_dataset["test"]) 

    return trainer,results

In [3]:
def dataset_loader(path) :
    with open(path, "r") as file:
        data = file.readlines()

    data_clean = [line for line in data if line.strip()]

    return data_clean

In [4]:
PATH = "/kaggle/input/arb-fr/"

data_arb = dataset_loader(PATH + "for_dataset_arb.txt")
data_fr = dataset_loader(PATH + "for_dataset_fr.txt")

In [5]:
# # for trying 
# data_arb = data_arb[:100] 
# data_fr = data_fr[:100]

In [6]:
# Création du dictionnaire
dataset_dict = {"translation": [{"arb": a, "fr": f} for a, f in zip(data_arb, data_fr)]}

# Création du dataset
dataset = Dataset.from_dict(dataset_dict)
# On va diviser notre dataset en deux parties
 #train_dataset =  DatasetDict({"train":test['train']})

train_test_dataset = dataset.train_test_split(test_size=0.2, seed= 42, shuffle= True)

test_val_dataset = train_test_dataset['test'].train_test_split(test_size= 0.5, seed= 42)

train_test_val_dataset = DatasetDict ({
    'train' : train_test_dataset['train'],
    'val'   : test_val_dataset['train'],
    'test'  : test_val_dataset['test']
})
train_test_val_dataset.save_to_disk("../Data/train_test_split")

Saving the dataset (0/1 shards):   0%|          | 0/10402 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1300 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1301 [00:00<?, ? examples/s]

In [7]:
import os
# À placer impérativement avant l'import de torch
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Les after....

In [8]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [9]:
#from src.models import training
from datasets import load_from_disk
from transformers import get_linear_schedule_with_warmup, AutoTokenizer,TrainerCallback,AutoModelForCausalLM, DataCollatorForSeq2Seq,AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer,EarlyStoppingCallback

### loading le train,test, val et model et tokenizer

In [10]:
train_test_val_dataset = load_from_disk("../Data/train_test_split")

### loading the model et tokenizer

In [11]:
nllb = "facebook/nllb-200-distilled-600M"
# model = AutoModelForSeq2SeqLM.from_pretrained(modele_name)
# tokenizer = AutoTokenizer.from_pretrained(modele_name)

In [12]:
trainer_nllb, nllb_evaluation = training(nllb, train_test_val_dataset)

nllb_evaluation

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

Map:   0%|          | 0/1300 [00:00<?, ? examples/s]

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

OutOfMemoryError: CUDA out of memory. Tried to allocate 3.09 GiB. GPU 0 has a total capacity of 14.56 GiB of which 1.83 GiB is free. Including non-PyTorch memory, this process has 12.73 GiB memory in use. Of the allocated memory 12.42 GiB is allocated by PyTorch, and 109.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://docs.pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf)

In [ ]:
#trainer_nllb.evaluate(train_test_val_dataset["test"])

## ByT5

In [ ]:
byt5 = "google/byt5-small"

trainer_byt5, evaluation_byt5 = training(byt5, train_test_val_dataset)

Loading weights:   0%|          | 0/172 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

Map:   0%|          | 0/160 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Map:   0%|          | 0/160 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

/usr/local/lib/python3.13/dist-packages/torch/autograd/function.py:596: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.13/dist-packages/transformers/generation/utils.py:1676: UserWarning: Using the model-agnostic default `max_length` (=21) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight'].

TrainOutput(global_step=150, training_loss=17.61640146891276, metrics={'train_runtime': 703.1272, 'train_samples_per_second': 11.378, 'train_steps_per_second': 0.213, 'total_flos': 1837499154432000.0, 'train_loss': 17.61640146891276, 'epoch': 50.0})

### Afri-byt5

In [ ]:
model_afri = "masakhane/afri-byt5-base"

trainer_afri = training(model_afri, train_test_val_dataset)
trainer_afri.train()